name: Render Quarto Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        run: |
          curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.149/quarto-1.1.149-linux-amd64.deb
          sudo dpkg -i quarto-1.1.149-linux-amd64.deb

      - name: Install Extension sellorm/quarto-social-embeds
        run: |
          sudo apt-get install -y expect
          expect -c '
          spawn quarto install extension sellorm/quarto-social-embeds
          expect "Do you trust the authors of this extension (Y/n)"
          send "Yes\r"
          expect "Would you like to continue (Y/n)"
          send "Yes\r"
          interact
          '

      - name: Render website into _site
        run: quarto render

      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          keep_files: false